# Generated by Django 4.1.5 on 2023-01-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
