# Generated by Django 4.1.7 on 2023-03-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_demo_user",
            field=models.BooleanField(default=False),
        ),
    ]
