# Generated by Django 4.1.5 on 2023-01-31 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("skyrim_helper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playercharacter",
            name="experience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playercharacter",
            name="ore",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playercharacter",
            name="plants",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playercharacter",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_characters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="playercharacter",
            name="septims",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playercharacter",
            name="soul_gems",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
