# Generated by Django 4.1.5 on 2023-01-07 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_usergame_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='abreviation',
            new_name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='gbId',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='user',
        ),
        migrations.AddField(
            model_name='platform',
            name='users',
            field=models.ManyToManyField(related_name='owned_platforms', through='api.UserPlatform', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='platform',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
