/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedPlayerCharacter
 */
export interface PatchedPlayerCharacter {
    /**
     * 
     * @type {string}
     * @memberof PatchedPlayerCharacter
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedPlayerCharacter
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedPlayerCharacter
     */
    soulGems?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedPlayerCharacter
     */
    ore?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedPlayerCharacter
     */
    experience?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedPlayerCharacter
     */
    plants?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedPlayerCharacter
     */
    septims?: number;
}

/**
 * Check if a given object implements the PatchedPlayerCharacter interface.
 */
export function instanceOfPatchedPlayerCharacter(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedPlayerCharacterFromJSON(json: any): PatchedPlayerCharacter {
    return PatchedPlayerCharacterFromJSONTyped(json, false);
}

export function PatchedPlayerCharacterFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedPlayerCharacter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'soulGems': !exists(json, 'soul_gems') ? undefined : json['soul_gems'],
        'ore': !exists(json, 'ore') ? undefined : json['ore'],
        'experience': !exists(json, 'experience') ? undefined : json['experience'],
        'plants': !exists(json, 'plants') ? undefined : json['plants'],
        'septims': !exists(json, 'septims') ? undefined : json['septims'],
    };
}

export function PatchedPlayerCharacterToJSON(value?: PatchedPlayerCharacter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'name': value.name,
        'soul_gems': value.soulGems,
        'ore': value.ore,
        'experience': value.experience,
        'plants': value.plants,
        'septims': value.septims,
    };
}

