/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * serializer for user game
 * @export
 * @interface UserGame
 */
export interface UserGame {
    /**
     * 
     * @type {number}
     * @memberof UserGame
     */
    readonly id: number;
    /**
     * 
     * @type {boolean}
     * @memberof UserGame
     */
    isFavorited: boolean;
    /**
     * 
     * @type {number}
     * @memberof UserGame
     */
    giantbombGame: number;
}

/**
 * Check if a given object implements the UserGame interface.
 */
export function instanceOfUserGame(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "isFavorited" in value;
    isInstance = isInstance && "giantbombGame" in value;

    return isInstance;
}

export function UserGameFromJSON(json: any): UserGame {
    return UserGameFromJSONTyped(json, false);
}

export function UserGameFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGame {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'isFavorited': json['isFavorited'],
        'giantbombGame': json['giantbomb_game'],
    };
}

export function UserGameToJSON(value?: UserGame | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isFavorited': value.isFavorited,
        'giantbomb_game': value.giantbombGame,
    };
}

