# Generated by Django 4.1.5 on 2023-02-12 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import resource_tracker.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameInstance",
            fields=[
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "join_code",
                    models.CharField(
                        default=resource_tracker.models.create_random_join_code,
                        max_length=4,
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GameTemplate",
            fields=[
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlayerResourceTemplate",
            fields=[
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("overridable_ranges", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
                ("min_ammount", models.IntegerField(default=-2147483647)),
                ("max_ammount", models.IntegerField(default=2147483647)),
                (
                    "game_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_resource_templates",
                        to="resource_tracker.gametemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlayerResourceInstance",
            fields=[
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_ammount", models.IntegerField(default=0)),
                ("min_ammount_override", models.IntegerField(blank=True, null=True)),
                ("max_ammount_override", models.IntegerField(blank=True, null=True)),
                (
                    "game_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resource_tracker.gameinstance",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resource_tracker.player",
                    ),
                ),
                (
                    "resource_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resource_tracker.playerresourcetemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="gametemplate",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resource_tracker.player",
            ),
        ),
        migrations.CreateModel(
            name="GameResourceTemplate",
            fields=[
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("overridable_ranges", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
                ("min_ammount", models.IntegerField(default=-2147483647)),
                ("max_ammount", models.IntegerField(default=2147483647)),
                (
                    "game_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_resource_templates",
                        to="resource_tracker.gametemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GameResourceInstance",
            fields=[
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_ammount", models.IntegerField(default=0)),
                (
                    "game_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resource_tracker.gameinstance",
                    ),
                ),
                (
                    "resource_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resource_tracker.gameresourcetemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="gameinstance",
            name="game_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resource_tracker.gametemplate",
            ),
        ),
        migrations.AddField(
            model_name="gameinstance",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_game_instances",
                to="resource_tracker.player",
            ),
        ),
        migrations.AddField(
            model_name="gameinstance",
            name="players",
            field=models.ManyToManyField(to="resource_tracker.player"),
        ),
    ]
