# Generated by Django 4.1.5 on 2023-02-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_tracker", "0002_specialdie_specialdieface"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerresourceinstance",
            name="max_ammount_override",
        ),
        migrations.RemoveField(
            model_name="playerresourceinstance",
            name="min_ammount_override",
        ),
        migrations.AddField(
            model_name="playerresourceinstance",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="gameresourcetemplate",
            name="max_ammount",
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name="gameresourcetemplate",
            name="min_ammount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playerresourcetemplate",
            name="max_ammount",
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name="playerresourcetemplate",
            name="min_ammount",
            field=models.IntegerField(default=0),
        ),
    ]
