# Generated by Django 4.1.7 on 2023-02-23 03:27

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "resource_tracker",
            "0005_rolllogentry_created_rolllogentry_is_archived_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolllogentry",
            name="die",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roll_entries",
                to="resource_tracker.specialdie",
            ),
        ),
        migrations.AlterField(
            model_name="rolllogentry",
            name="face",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roll_entries",
                to="resource_tracker.specialdieface",
            ),
        ),
        migrations.CreateModel(
            name="GamePlayer",
            fields=[
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "game_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resource_tracker.gameinstance",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resource_tracker.player",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="playerresourceinstance",
            name="game_player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resource_tracker.gameplayer",
            ),
        ),
        migrations.AddField(
            model_name="rolllog",
            name="game_player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resource_tracker.gameplayer",
            ),
        ),
    ]
