# Generated by Django 4.1.7 on 2023-02-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_tracker", "0007_auto_20230223_0328"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rolllog",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="gameinstance",
            name="players",
        ),
        migrations.RemoveField(
            model_name="playerresourceinstance",
            name="game_instance",
        ),
        migrations.RemoveField(
            model_name="playerresourceinstance",
            name="owner",
        ),
        migrations.AddField(
            model_name="gameinstance",
            name="game_players",
            field=models.ManyToManyField(
                through="resource_tracker.GamePlayer", to="resource_tracker.player"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gameplayer",
            unique_together={("player", "game_instance")},
        ),
        migrations.RemoveField(
            model_name="rolllog",
            name="game_instance",
        ),
        migrations.RemoveField(
            model_name="rolllog",
            name="player",
        ),
    ]
