# Generated by Django 4.1.7 on 2023-02-23 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resource_tracker", "0008_alter_rolllog_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerresourceinstance",
            name="game_player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resource_tracker.gameplayer",
            ),
        ),
        migrations.AlterField(
            model_name="rolllog",
            name="game_player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resource_tracker.gameplayer",
            ),
        ),
    ]
