# Generated by Django 4.1.7 on 2023-02-23 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resource_tracker", "0009_alter_playerresourceinstance_game_player_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SpecialDie",
            new_name="Die",
        ),
    ]
