# Generated by Django 4.1.7 on 2023-02-23 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resource_tracker", "0010_rename_specialdie_die"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SpecialDieFace",
            new_name="DieFace",
        ),
    ]
