# Generated by Django 4.1.7 on 2023-02-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resource_tracker", "0011_rename_specialdieface_dieface"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameresourcetemplate",
            name="game_template",
        ),
        migrations.DeleteModel(
            name="GameResourceInstance",
        ),
        migrations.DeleteModel(
            name="GameResourceTemplate",
        ),
    ]
