# Generated by Django 4.1.7 on 2023-02-26 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resource_tracker", "0013_remove_gameinstance_game_players_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerresourceinstance",
            name="game_player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resource_tracker.gameplayer",
            ),
        ),
    ]
