# Generated by Django 4.1.7 on 2023-02-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resource_tracker", "0014_alter_playerresourceinstance_game_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerresourceinstance",
            name="game_player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_resource_instances",
                to="resource_tracker.gameplayer",
            ),
        ),
    ]
