# Generated by Django 4.1.7 on 2023-03-08 18:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "resource_tracker",
            "0018_alter_gameinstance_user_alter_gameplayer_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameinstance",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="gametemplate",
            name="owner",
        ),
        migrations.AlterUniqueTogether(
            name="gameplayer",
            unique_together={("user", "game_instance")},
        ),
        migrations.RemoveField(
            model_name="gameplayer",
            name="player",
        ),
    ]
