# Generated by Django 4.1.7 on 2023-03-08 18:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "resource_tracker",
            "0019_remove_gameinstance_owner_remove_gametemplate_owner_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="gameinstance",
            old_name="user",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="gameplayer",
            old_name="user",
            new_name="player",
        ),
        migrations.RenameField(
            model_name="gametemplate",
            old_name="user",
            new_name="owner",
        ),
        migrations.AlterUniqueTogether(
            name="gameplayer",
            unique_together={("player", "game_instance")},
        ),
    ]
