# Generated by Django 4.1.7 on 2023-03-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resource_tracker", "0020_rename_user_gameinstance_owner_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Player",
        ),
    ]
